### ISSUE TITLE
后台登陆成功，又跳回后台首页

### ISSUE THREAD

**Issue by chenye2017** [fingerQin/www.phpjieshuo.com#1]

**Comment by fingerQin** [comment]
我在判断用户是否登录的时候，是通过读取登录成功之后设置在 Cookie 里面的 auth_token。如果登录成功之后，读取不到这个值就会继续跳转到登录页面。你可以查看一下登录成功之后是否成功设置了 auth_token 的值。注意，一定要配置虚拟的域名。不能以 127.0.0.1 这种方式访问。

**Comment by chenye2017** [comment]
可以了，谢谢
